### ISSUE TITLE
http:// to //

### ISSUE THREAD

**Issue by scola84** [thgh/rollup-plugin-livereload#1]
Works nice, only could you change http:// to // in https://github.com/thgh/rollup-plugin-livereload/blob/master/src/index.js#L20? Then it works with secure connections as well...

**Comment by thgh** [comment]
By default, livereload will [create an http server](https://www.npmjs.com/package/livereload#api-options). You have to pass `{ https: { certificate stuff } }` to have it run on https.

Update coming soon.
