### ISSUE TITLE
Uncaught ReferenceError: ProtocolError is not defined

### ISSUE THREAD

**Issue by kekeqy** [thgh/rollup-plugin-livereload#13]
Uncaught ReferenceError: ProtocolError is not defined
    at Object.LiveReload.connector.Connector.error (livereload.js?snipver=1:345)
    at Object.Connector.protocolParser.Parser.error (livereload.js?snipver=1:31)
    at Parser.exports.Parser.Parser.process (livereload.js?snipver=1:614)
    at Connector.exports.Connector.Connector._onmessage (livereload.js?snipver=1:165)
    at WebSocket.<anonymous> (livereload.js?snipver=1:87)
LiveReload.connector.Connector.error @ livereload.js?snipver=1:345
Connector.protocolParser.Parser.error @ livereload.js?snipver=1:31
exports.Parser.Parser.process @ livereload.js?snipver=1:614
exports.Connector.Connector._onmessage @ livereload.js?snipver=1:165
(anonymous) @ livereload.js?snipver=1:87

**Comment by thgh** [comment]
Did you find out what happened?

**Comment by kekeqy** [comment]
This error is prompted, but it still works.

**Comment by kekeqy** [comment]
@thgh It's a probabilistic problem, and I noticed that the console printed a warning message before throwing this error.

> DevTools failed to parse SourceMap: http://127.0.0.1/build/thing.js.map

My guess is that the sourcemap file hasn't been written yet, but the browser refreshes, and the souremap parsing fails,then it throws an exception.

This is my project address, I hope you can help me look at it.
[https://github.com/ThingTS/ThingTS](url)

**Comment by thgh** [comment]
You could try upgrading livereload@0.6.0 to 0.7.0

Or reimplement it using https://www.npmjs.com/package/tiny-lr
