### ISSUE TITLE
css injection

### ISSUE THREAD

**Issue by ca-miked** [thgh/rollup-plugin-livereload#17]
Hi,

Is it possible to have css file updates injected into the page as opposed to just reloading the browser window? This is a substantial workflow regression compared to webpack hot reload/css injection.

Thanks

**Comment by ca-miked** [comment]
Update: I was able to get this working by providing the direct path to the css file that is being compiled vs the entier `dist` folder. The downside is no reload/injection for .js file updates. Ideally, we could pass an array and/or GLOB options instead of a single string.

**Comment by thgh** [comment]
You can actually pass an array to `watch`. Does that solve your issue?

**Comment by ca-miked** [comment]
Ahhh, my apologies i was still running v0.6.0. After upgrading to 1.0 it works now. Thanks again!
