### ISSUE TITLE
Auto-assign a port

### ISSUE THREAD

**Issue by appsforartists** [thgh/rollup-plugin-livereload#23]
To properly test the project I'm working on, I need two separate apps running at the same time.  I've got similar rollup configs for each.

Both are using `firebase serve` for their static assets.  It has the handy feature of finding its own port if the default one is taken:

```
[1] ⚠  hosting: Port 5000 is not available. Trying another port...
[1] i  hosting: Serving hosting files from: packages/ui/site
[1] ✔  hosting: Local server: http://0.0.0.0:5005
```

Would you be amenable to a PR that added this feature to `rollup-plugin-livereload`?

This passage from the upstream [changelog](https://github.com/napcs/node-livereload) leads me to believe that the plugin is the correct place to fix this:

> You can now use server.on 'error' in your code to catch the "port in use" message gracefully. The CLI now handles this nicely as well.

**Comment by thgh** [comment]
If this doesn't add much dependencies, then yes! Could you build the feature with https://github.com/Rich-Harris/port-authority ?

If you just want to solve your problem => assign a random port once per project
For example: `livereload({ port: 51823 })`.

**Comment by appsforartists** [comment]
*poke poke*

**Comment by thgh** [comment]
Do you mind resolving the merge conflicts?

**Comment by avimar** [comment]
Ah, looks like this would nicely solve https://github.com/thgh/rollup-plugin-livereload/issues/51

**Comment by thgh** [comment]
Checkout out rollup-plugin-livereload@2.0.0 🎉
