### ISSUE TITLE
Update livereload version from @0.8.0 @0.8.1

### ISSUE THREAD

**Issue by ArtemNikolaev** [thgh/rollup-plugin-livereload#26]
Please, update `livereload` dependency from @0.8.0 to @0.8.1 to fix security alert from github.

main problem was in `ws` dependency, which is used by `livereload`, but livereload already fix this issue in @0.8.1, if you update thi dependency version it will fix this problem auto.

Thx!

**Comment by thgh** [comment]
I will keep 0.8.0 until proper confirmation that v0.8.1 works and is safe.
https://github.com/thgh/rollup-plugin-livereload/pull/25
