### ISSUE TITLE
Does not work as expected

### ISSUE THREAD

**Issue by eakarpov** [thgh/rollup-plugin-livereload#31]
Plugin does not reload the build for the defined folder.

`livereload('src'),`

It reloads while editing rollup config only and breaks with the following error:

`Error: listen EADDRINUSE: address already in use :::35729`

**Comment by thgh** [comment]
It's best to let it watch your build files, not your source => `livereload('build')`

Editing Rollup config while in watch mode will indeed break the plugin, solution described in https://github.com/thgh/rollup-plugin-livereload/issues/30

**Comment by thgh** [comment]
This is probably fix, will close for now. Always welcome to update with more info!
