### ISSUE TITLE
Old browser compatible

### ISSUE THREAD

**Issue by cjahv** [thgh/rollup-plugin-livereload#35]
https://github.com/thgh/rollup-plugin-livereload/blob/4311f23045e8c37335e337a88a89a0d477fb63a7/src/index.js#L30

`l.head.appendChild(r)` does not work in ie8

https://stackoverflow.com/questions/17100246/document-head-appendchildelement-ie-ie7-and-ie8

**Comment by jokin** [comment]
I have the same problem, not with IE8 but with some devices that use a legacy browser, Opera tv with chromium 44. 

there should be a way to configure the build to make an es5 compatible build.
