### ISSUE TITLE
some

### ISSUE THREAD

**Issue by XdyGoGo** [thgh/rollup-plugin-livereload#45]
I have the dir named example/index.html。when I livereload('./example'),  It does not work

**Comment by jdoubleu** [comment]
Are you starting the Node.js process WSL as well or from Windows?

Node.js's `file.watch` might not work accross Windows `<>` WSL.

**Comment by jonkoops** [comment]
Considering this looks to be a bug in WSL and not this library, I will go ahead and close this issue. If anyone has detailed steps on how to reproduce this issue and believes it is still relevant please do let me know.

**Comment by thgh** [comment]
Would be interesting if it was possible to test this in Github actions
