### ISSUE TITLE
Livereload breaks when TypeScript emits error

### ISSUE THREAD

**Issue by edwinm** [thgh/rollup-plugin-livereload#49]
I have a simple rollup config with `rollup-plugin-livereload` and `@rollup/plugin-typescript`. When I save a file with a TypeScript error, the error appears in the console. When I fix this error and save the file, reloading doesn't work anymore. I have to quit and restart rollup.

Expected: Livereload should keep working, even after a TypeScript error.

Versions:

        "@rollup/plugin-typescript": "^4.1.1",
        "rollup": "^2.10.2",
        "rollup-plugin-livereload": "^1.3.0",
        "rollup-plugin-terser": "^5.3.0",
        "tslib": "^2.0.0",
        "typescript": "^3.9.2"

This is my `rollup.config.js`:

`
import typescript from '@rollup/plugin-typescript';
import livereload from 'rollup-plugin-livereload';
import { terser } from "rollup-plugin-terser";

export default {
  input: 'src/index.ts',
  output: {
    file: 'dist/bundle.min.js',
    format: 'iife',
    name: 'bundle',
  },
  plugins: [livereload(), typescript(), terser()],
};
`

**Comment by vicrazumov** [comment]
this is related to the typescript plugin behavior: https://github.com/rollup/plugins/issues/272

adding `noEmitOnError: false` to both `tsconfig.json` and `rollup.config.js` helps
