### ISSUE TITLE
Make injection of code in JavaScript optional

### ISSUE THREAD

**Issue by edwinm** [thgh/rollup-plugin-livereload#50]
I like to have a new configuration option to turn off livereload code injection in the generated JavaScript bundle.

I like to use a browser extension to enable live reload in the browser.

Advantages:
1) I don't need multiple rollup configurations (one with livereload and one for deployment).
2) I'm sure I'm testing with code that is the same as the deployed code.

**Comment by thgh** [comment]
Makes sense, PR welcome!

You can work around it like this:
```js
  plugins: [
    { ...livereload(), banner: null }
  ]
```
