### ISSUE TITLE
`rollup -c -w` exits without any error.

### ISSUE THREAD

**Issue by avimar** [thgh/rollup-plugin-livereload#51]
I have some new data, so I thought I'd gather the relevant issues here.

>Even worst for me with svelte template: command **exit** (rollup -c -w) without any error. 
>Removing livereload from the config solve the issue: command works fine.
> I was wondering if it was only me but seems like I'm not alone: https://github.com/sveltejs/template/issues/133
_Originally posted by @sansnom in https://github.com/thgh/rollup-plugin-livereload/issues/46#issuecomment-645471396_

I've had this issue sometimes and just now I found that I accidentally had another terminal with `rollup -c -w` running in the same working directory.

So somehow the watching AND livereload plugin has a problem.

With one running instance with watch and livereload, the second instance...
- rollup build: works OK.
- rollup watch, livereload not called: works OK.
- rollup watch with livereload enabled: silently exits. <-- our issue

**Comment by avimar** [comment]
Oh! Figured it out, I think.
It seems livereload always binds to port 35729. It's running into a port conflict.

I ran into the same issue when I had rollup with livereload in two different work directories.

So we can launch an instance on a different port - https://github.com/thgh/rollup-plugin-livereload/blob/1bbcf8f2ea20c2adf554317b0c00b8355d7aaaca/src/index.js#L22

e.g. `!production && livereload({watch: 'public', port: 35730}),`

Not sure the best way to proceed - try to launch and try again with a new port? Always pass a random port? Possibly other options.

**Comment by avimar** [comment]
Weird, livereload seems to check for port in use but all the console.log messages are getting silently swallowed.
https://github.com/napcs/node-livereload/blob/2e7e6976b33bdc8d923193a5710d0617e5b4c03c/lib/command.js#L96

**Comment by sansnom** [comment]
Nice catch ! On Windows, the port is taken by "Intel(R) Active Management Technology Local Manageability Service" (LMS.exe).

**Comment by avimar** [comment]
> Nice catch ! On Windows, the port is taken by "Intel(R) Active Management Technology Local Manageability Service" (LMS.exe).

Oh wow, for me on windows 10, it was only taken when I was running a live reload in another cli.

Regardless, we have a port usage issue.

**Comment by LuisOcasio** [comment]
Running this install fixed this for me.

npm i rollup

https://www.npmjs.com/package/rollup

**Comment by thgh** [comment]
Thanks for creating an issue, please reopen if this still happens with rollup-plugin-livereload@2.0.0

**Comment by michelcouto** [comment]
I am facing this issue with any version (even latest 2.0.5).
After running `rollup -c -w`, with livereload configured, everything starts beautifully.
But, if I simply waits, without doing anything at all, it just exits.
Like this:
 Your application is ready~! 🚀

  - Local:      http://0.0.0.0:5000       
  - Network:    http://10.154.253.165:5000

────────────────── LOGS ──────────────────

Done in 42.42s.

So, in this case, after 42s, the livereload stops working.
If I try to reach the code in the browser, I can see that the server is still on... But, watch does nothing, which means, there is no recompiling happening after I change any code.

In the browser, I also see this error in the console, after those 42s.

WebSocket connection to 'ws://10.154.253.165:35729/livereload' failed: 
connect @ livereload.js?snipver=1:2232
(anonymous) @ livereload.js?snipver=1:2205
Timer._handler @ livereload.js?snipver=1:3913

If I change anything before those 42s, then it works great. I see a recompile, and there is a livereload in place.
(of course, this time varies... it is not only 42s, but it could be a bit more, a bit less).
Does anyone have any idea why that happens?
