### ISSUE TITLE
Default Svelte Template With LiveReload On Secure Local Dev Domain

### ISSUE THREAD

**Issue by robots4life** [thgh/rollup-plugin-livereload#52]
Hi Thomas
Perhaps with a bit of guidance and help from you a few people can enjoy your rollup-plugin-livereload with Svelte on secure local dev domains. In this thread there is a comment that might help us get there. [https://github.com/cytopia/devilbox/issues/709#issuecomment-653395243](https://github.com/cytopia/devilbox/issues/709#issuecomment-653395243) Perhaps you kindly have a bit of time to have a look? :+1: 

What I am wondering is this. The default Svelte template does not use [https://www.npmjs.com/package/rollup-plugin-serve](https://www.npmjs.com/package/rollup-plugin-serve) and it is not clear to me if the [options in the readme](https://github.com/thgh/rollup-plugin-livereload#options) of your rollup-plugin-livereload using `https` are available without rollup-plugin-serve?

What I am trying to do is tell rollup-plugin-livereload in the `rollup.config.js` file to use `https` and point it to the `key` and `cert` files provided with the local dev setup. Is that possible without `rollup-plugin-serve`? Perhaps we are close to getting this done. Posted in Svelte Discord and searched on SO with little results, have a feeling we are close. Fingers crossed. :v:

**Comment by thgh** [comment]
I haven't used livereload with https, I just assume their [docs](https://www.npmjs.com/package/livereload#server-api) are correct 😄 

@wangchou has [updated](https://github.com/thgh/rollup-plugin-livereload/commit/e16065d696af078d93578f68148985f1a21a5955#diff-04c6e90faac2675aa89e2176d2eec7d8) the https example, so he may know more about this!

**Comment by robots4life** [comment]
@thgh and @wangchou I will see if I manage to integrate your solution into my [workflow](https://github.com/cytopia/devilbox/issues/709) and report back in any case.

**Comment by robots4life** [comment]
@thgh and @wangchou I can confirm with your config example it does work, thank you. :sunflower:

**Comment by robots4life** [comment]
Here is a Svelte template working with Devilbox and LiveReload on a secure local development domain. https://github.com/robots4life/svelte-slr Thanks to your input and some further digging I could resolve the original issue as well.
