### ISSUE TITLE
Support for file urls (electron)

### ISSUE THREAD

**Issue by ramiroaisen** [thgh/rollup-plugin-livereload#54]
Hi, a little modification to the script would allow the plugin work in electron for file urls, check if the location is a file url and set http:// instead of // at the start of the script url

This is a nice plugin, thank you :+1:

**Comment by thgh** [comment]
PR welcome, make sure that https works too!

**Comment by ramiroaisen** [comment]
Will do 

> PR welcome, make sure that https works too!

I'll make it, sure
