### ISSUE TITLE
Doesn't work with rollup-plugin-serve

### ISSUE THREAD

**Issue by brianblakely** [thgh/rollup-plugin-livereload#6]
My rollup config:

```javascript
import serve from 'rollup-plugin-serve';
import livereload from 'rollup-plugin-livereload';

export default {
  entry: `src/index.js`,
  dest: `docs/script.js`,

  plugins: [
    serve({
      open: true,
      contentBase: `docs`,
    }),
    livereload()
  ],

  format: `iife`
};
```

Then, I run `rollup --config --watch`.  The app loads on port 10001, but it doesn't livereload upon bundle changes.  In fact, the bundle doesn't get compiled at all anymore! Removing this plugin fixes everything.

**Comment by zhenizhui** [comment]
same.

**Comment by clavery63** [comment]
Is this still an issue?  This plugin is working for me with rollup-plugin-serve now.  I'm using the rollup.plugin.js file you pasted above

**Comment by sca-** [comment]
livereload + serve doesn't work for me
my rollup.config.js:
```javascript
import babel from 'rollup-plugin-babel'
import serve from 'rollup-plugin-serve'
import replace from 'rollup-plugin-replace'
import commonjs from 'rollup-plugin-commonjs'
import livereload from 'rollup-plugin-livereload'
import nodeResolve from 'rollup-plugin-node-resolve'

export default {
  entry: './src/index.js',
  dest: './dist/index.bundle.js',
  format: 'iife',
  plugins: [
    babel({
      exclude: 'node_modules/**'
    }),
    nodeResolve({
      jsnext: true
    }),
    commonjs({
      include: 'node_modules/**',
      namedExports:
      {
        './node_modules/react/react.js': [
          'cloneElement',
          'createElement',
          'PropTypes',
          'Children',
          'Component'
        ]
      }
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify('production')
    }),
    serve(),
    livereload()
  ]
}
```

**Comment by thgh** [comment]
Hello everyone, thank you for taking the time to create an issue on this repository. It's been more than a year since I developed a project using Rollup. Let me know if someone wants to maintain this project.

**Comment by JamesTheHacker** [comment]
Works for me guys. Not sure if my config is of any use but I'll share it anyway

```
import resolve from 'rollup-plugin-node-resolve';
import babel from 'rollup-plugin-babel';
import livereload from 'rollup-plugin-livereload';
import serve from 'rollup-plugin-serve';
import commonjs from 'rollup-plugin-commonjs';
import postcss from 'rollup-plugin-postcss';
import sass from 'node-sass';
import cssnano from 'cssnano';

const cssExportMap = {};

export default {
  input: 'src/main.js',
  output: {
    file: 'dist/app.js',
    format: 'iife'
  },
  plugins: [
    postcss({
      preprocessor: (content, id) => new Promise((resolve, reject) => {
        const result = sass.renderSync({ file: id })
        resolve({ code: result.css.toString() })
      }),
      plugins: [
        cssnano(),
      ],
      sourceMap: false,
      extract: true,
      extensions: [ '.css', '.scss', '.sass' ],
    }),
    commonjs({
      namedExports: {
        'node_modules/validate.js/validate': [ 'validate' ]
      }
    }),
    resolve(),
    babel({
      exclude: [
        './node_modules/**',
        './src/css/**',
      ],
    }),
    serve('dist'),
    livereload('dist'),
  ]
};
```

**Comment by jhonnymichel** [comment]
It is working for me as well. It worked when I specified BOTH my `src` directory and my `dist` one.
Not working:
`import serve from 'rollup-plugin-serve';
import livereload from 'rollup-plugin-livereload';
import sourcemaps from 'rollup-plugin-sourcemaps';
import config from './rollup.config';

const { input } = config;
export default {
  input,
  output: {
    file: 'dev/xexeu-view.js',
    format: 'iife',
    name: "Xexeu"
  },
  sourceMap: true,
  plugins: [
    serve('devServer'),
    livereload('devServer'),
    sourcemaps()
  ]
}`

working:

`import serve from 'rollup-plugin-serve';
import livereload from 'rollup-plugin-livereload';
import sourcemaps from 'rollup-plugin-sourcemaps';
import config from './rollup.config';

const { input } = config;
export default {
  input,
  output: {
    file: 'dev/xexeu-view.js',
    format: 'iife',
    name: "Xexeu"
  },
  sourceMap: true,
  plugins: [
    serve('devServer'),
    livereload({
      watch: [
        path.resolve(__dirname, 'dist'),
        path.resolve(__dirname, 'src')
      ],
    }),
    sourcemaps()
  ]
}`

**Comment by jhonnymichel** [comment]
It works when you specify both your `src`and `dist`folders to the livereload config, just as @JamesTheHacker did.

**Comment by homerjam** [comment]
Works for me but doesn't wait for the bundle to finish building so I end up manually refreshing anyway!

**Comment by ChristianUlbrich** [comment]
Specifying **both** `src` and `dist` folders, triggers the reload always twice. It will work (i.e. reload once and use current bundle), if you specify just the `dist` folder, *or more precisely* the folder that will contain your generated bundle.

Looking at the code, the problem is, that if you do not specify an option to `livereload()` it won't use your configs `dest` but the current working dir. This is always a problem, if your bundle is in **not in the cwd()** as OP. This is in contrast, to what the readme says:

> By default it watches the bundle dest. If you also have css output, pass the folder to which the build files are written.

Or at least it could be more precise.

@brianblakely 
```javascript
import serve from 'rollup-plugin-serve';
import livereload from 'rollup-plugin-livereload';

export default {
  entry: `src/index.js`,
  dest: `docs/script.js`,

  plugins: [
    serve({
      open: true,
      contentBase: `docs`,
    }),
    livereload('docs')
  ],

  format: `iife`
};
```
Note the changed param to `livereload()`, should fix it for you!

**Comment by cjh9** [comment]
@ChristianUlbrich Is it possible to avoid livereload refreshing twice?

**Comment by thgh** [comment]
Yes, try to pass `{ delay: 500, watch: 'dist' }`
For more options, see https://www.npmjs.com/package/livereload

**Comment by ChristianUlbrich** [comment]
@cjh9 Yeah, just *do not* specify *two* folders for watching and then I'll will only reload once.

**Comment by littlstonee** [comment]
I think the theory behind this plugin is detecting file change to trigger browser reload which is actually similar to rollup --watch build mode.
So setting this plugin only watch output folder makes sence if rollup build started with --watch option.

Short summary:
Rollup watches `src` folder, and rebuilds  files into `dist`  when files in `src`  changed.
This plugin watches `dist` folder, and reloads browser when files in `dist`  changed.
