### ISSUE TITLE
Security vulnerability via livereload via jsdom via ws (please bump to ws@>=7.6.4)

### ISSUE THREAD

**Issue by jan-musi** [thgh/rollup-plugin-livereload#62]
Thank you for this helpful library! :)

See https://github.com/websockets/ws/releases/tag/7.4.6

I'm not sure how best to fix this here, because [this library's exposure](https://github.com/thgh/rollup-plugin-livereload/blob/master/yarn.lock#L232) to the `ws` vulnerability is [through an outdated version](https://github.com/thgh/rollup-plugin-livereload/blob/master/yarn.lock#L159) of [`livereload`](https://github.com/livereload/livereload-js) (0.9.1 vs. 3.3.2). Perhaps this library should add `ws@>=7.6.4` as a direct dependency, or perhaps this library can afford to wait to upgrade to the next release of [`livereload`](https://github.com/livereload/livereload-js) after it [mitigates its exposure](https://github.com/livereload/livereload-js/pull/101).

**Comment by thgh** [comment]
This has been resolved in v2.0.2 🎉
