### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by MarkTiedemann** [thgh/rollup-plugin-livereload#69]
When connecting to a local dev server at `http://[::1]/`, the URL is incorrectly calculated as `//[:35729/livereload.js?snipver=1`.

**Comment by MarkTiedemann** [comment]
`(self.location.host || 'localhost').split(':')[0]` is used to calculate the hostname. If `location.host` is `"[::1]"`, it doesn't work.

**Comment by jdoubleu** [comment]
Could you visit your site through an IPv6 IP address, open the developer console, enter
```js
window.location.hostname
```
and verify, that it yields `[::1]`?

If it does, I think #71 will fix this issue.

**Comment by MarkTiedemann** [comment]
Yes, it does. Thanks, @jdoubleu!
