### ISSUE TITLE
Rename the `master` branch to `main`

### ISSUE THREAD

**Issue by jonkoops** [thgh/rollup-plugin-livereload#81]
Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from `master`. See more about GitHub's initiative [here](https://github.com/github/renaming/tree/main).

**Comment by jonkoops** [comment]
@thgh since I have no access to the repository settings, can I ask you to do this for me?

**Comment by thgh** [comment]
main 👍
